### ISSUE TITLE
Android build failing after upgrading to 8.0.0

### ISSUE THREAD

**Issue by AngadSethi** [zoho/SalesIQ-Mobilisten-ReactNative#79]
Hello,

I recently upgraded to `8.0.0`, and now my Android builds are failing with this error. Can you please help me out?

```
> Task :react-native-zohosalesiq-mobilisten:compileDebugJavaWithJavac FAILED
/home/expo/workingdir/build/node_modules/react-native-zohosalesiq-mobilisten/android/src/main/java/com/zohosalesiq/reactlibrary/RNZohoSalesIQ.java:1633: error: no suitable method found for getResources(ResourceType,String,String,String,int,int,<anonymous ResourcesListener>)
        executeIfResourceTypeIsValid(type, callback, () -> ZohoSalesIQ.KnowledgeBase.getResources(getResourceType(type), departmentID, parentCategoryID, searchKey, page, limit, new ResourcesListener() {
                                                                                    ^
    method KnowledgeBase.getResources(ResourceType,String,String,String,boolean,ResourcesListener) is not applicable
      (actual and formal argument lists differ in length)
    method KnowledgeBase.getResources(ResourceType,boolean,ResourcesListener) is not applicable
      (actual and formal argument lists differ in length)
    method KnowledgeBase.getResources(ResourceType,String,String,String,int,int,boolean,ResourcesListener) is not applicable
      (actual and formal argument lists differ in length)
Note: /home/expo/workingdir/build/node_modules/react-native-zohosalesiq-mobilisten/android/src/main/java/com/zohosalesiq/reactlibrary/RNZohoSalesIQ.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/expo/workingdir/build/node_modules/react-native-zohosalesiq-mobilisten/android/src/main/java/com/zohosalesiq/reactlibrary/RNZohoSalesIQ.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
```

**Comment by bhahirathan-mb-11956** [comment]
Hi @AngadSethi,

We apologize for any inconvenience caused, we have fixed this issue. We recommend you update to the latest version [8.0.1](https://github.com/zoho/SalesIQ-Mobilisten-ReactNative/releases/tag/v8.0.1), and verify. Please feel free to write back to us at (support@zohosalesiq.com) if the issue persists.

Regards,
Bhahirathan M
Zoho SalesIQ.

**Comment by AngadSethi** [comment]
Works like a charm. Thanks a ton for the quick resolution, @bhahirathan-mb-11956! 😄
